# Generated by Django 4.2.20 on 2025-05-03 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deferment_reason',
            field=models.TextField(blank=True, help_text='Причина отсрочки (если есть)'),
        ),
        migrations.AddField(
            model_name='application',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA (например, 3.75)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_deferment',
            field=models.BooleanField(db_index=True, default=False, help_text='Наличие отсрочки'),
        ),
        migrations.AddField(
            model_name='application',
            name='iin',
            field=models.CharField(default=777777777777, help_text='Индивидуальный идентификационный номер (12 цифр)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИИН должен быть из 12 цифр.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('resume', 'Резюме'), ('photo', 'Фото'), ('diploma', 'Диплом'), ('attestat', 'Аттестат'), ('id_document', 'Удостоверение личности'), ('conscript_ticket', 'Приписной билет')], help_text='Тип вложения', max_length=20, null=True),
        ),
    ]
